# Copyright 2026 The pubkit Authors
# SPDX-License-Identifier: Apache-2.0
"""The canonical Post IR.

Everything upstream (loaders) produces this; everything downstream (checks,
planner, adapters) consumes it. No platform detail is allowed in this module —
that is the whole point of it existing.
"""
from __future__ import annotations

import hashlib
import json
from enum import Enum
from pathlib import Path
from typing import Annotated, Literal

from pydantic import BaseModel, Field, field_validator


class BlockType(str, Enum):
    HEADING = "heading"
    PARAGRAPH = "paragraph"
    CODE = "code"
    QUOTE = "quote"
    LIST = "list"
    TABLE = "table"
    FIGURE = "figure"
    EMBED = "embed"
    RULE = "rule"
    CALLOUT = "callout"


class _Block(BaseModel):
    model_config = {"extra": "forbid"}


class Heading(_Block):
    type: Literal[BlockType.HEADING] = BlockType.HEADING
    level: int = Field(ge=1, le=6)
    text: str
    #: Generated by the numbering pass. Never authored by hand (failure C2).
    number: str | None = None
    anchor: str | None = None


class Paragraph(_Block):
    type: Literal[BlockType.PARAGRAPH] = BlockType.PARAGRAPH
    #: Inline markdown is permitted here; adapters degrade it as needed.
    text: str


class Code(_Block):
    type: Literal[BlockType.CODE] = BlockType.CODE
    language: str = ""
    text: str


class Quote(_Block):
    type: Literal[BlockType.QUOTE] = BlockType.QUOTE
    text: str
    attribution: str | None = None


class ListBlock(_Block):
    type: Literal[BlockType.LIST] = BlockType.LIST
    ordered: bool = False
    items: list[str]


class Table(_Block):
    """A *semantic* table.

    Whether this ends up as a real table, a rendered PNG or a bulleted list is
    the planner's decision, taken per platform. Keeping it semantic here is
    what lets one source serve Medium (no tables) and Dev.to (tables) without
    forking the content.
    """

    type: Literal[BlockType.TABLE] = BlockType.TABLE
    caption: str | None = None
    header: list[str]
    rows: list[list[str]]
    #: Optional per-column alignment: "l" | "c" | "r"
    align: list[str] | None = None

    @field_validator("rows")
    @classmethod
    def _rectangular(cls, rows: list[list[str]], info) -> list[list[str]]:
        header = info.data.get("header") or []
        for i, row in enumerate(rows):
            if len(row) != len(header):
                raise ValueError(
                    f"row {i} has {len(row)} cells, header has {len(header)}"
                )
        return rows


class Figure(_Block):
    type: Literal[BlockType.FIGURE] = BlockType.FIGURE
    #: Reference into Document.assets. Never a filesystem path (failure B5/B6).
    asset_id: str
    caption: str | None = None
    alt: str | None = None


class Embed(_Block):
    type: Literal[BlockType.EMBED] = BlockType.EMBED
    url: str
    kind: Literal["youtube", "gist", "tweet", "codepen", "generic"] = "generic"


class Rule(_Block):
    type: Literal[BlockType.RULE] = BlockType.RULE


class Callout(_Block):
    type: Literal[BlockType.CALLOUT] = BlockType.CALLOUT
    style: Literal["note", "warning", "tip", "key"] = "note"
    title: str | None = None
    text: str


Block = Annotated[
    Heading | Paragraph | Code | Quote | ListBlock | Table | Figure | Embed | Rule | Callout,
    Field(discriminator="type"),
]


class Asset(BaseModel):
    model_config = {"extra": "forbid"}

    id: str
    path: Path
    alt: str = ""
    #: Set by the renderer when an asset is *generated* (e.g. a table PNG).
    generated_from: str | None = None

    @property
    def mime(self) -> str:
        return {
            ".png": "image/png",
            ".jpg": "image/jpeg",
            ".jpeg": "image/jpeg",
            ".gif": "image/gif",
            ".webp": "image/webp",
            ".svg": "image/svg+xml",
        }.get(self.path.suffix.lower(), "application/octet-stream")

    @property
    def animated(self) -> bool:
        return self.path.suffix.lower() == ".gif"


class SeriesRef(BaseModel):
    model_config = {"extra": "forbid"}

    id: str
    index: int = Field(ge=1)
    of: int = Field(ge=1)
    #: Populated during phase 1 of a two-phase publish (failure C3).
    sibling_urls: dict[int, str] = Field(default_factory=dict)


class Budget(BaseModel):
    """Length constraints, checked pre-flight (failure C4)."""

    model_config = {"extra": "forbid"}

    words: int | None = None
    tolerance: float = 0.15


class Document(BaseModel):
    model_config = {"extra": "forbid"}

    id: str
    title: str
    subtitle: str | None = None
    tags: list[str] = Field(default_factory=list)
    canonical_url: str | None = None
    blocks: list[Block] = Field(default_factory=list)
    assets: dict[str, Asset] = Field(default_factory=dict)
    series: SeriesRef | None = None
    budget: Budget | None = None
    #: Free-form, passed through to adapters that understand it.
    platform_overrides: dict[str, dict] = Field(default_factory=dict)

    # ---------------------------------------------------------------- helpers
    @property
    def word_count(self) -> int:
        parts: list[str] = []
        for b in self.blocks:
            if isinstance(b, (Paragraph, Quote, Callout)):
                parts.append(b.text)
            elif isinstance(b, Heading):
                parts.append(b.text)
            elif isinstance(b, ListBlock):
                parts.extend(b.items)
            elif isinstance(b, Table):
                parts.extend(b.header)
                for r in b.rows:
                    parts.extend(r)
        return len(" ".join(parts).split())

    @property
    def figures(self) -> list[Figure]:
        return [b for b in self.blocks if isinstance(b, Figure)]

    @property
    def tables(self) -> list[Table]:
        return [b for b in self.blocks if isinstance(b, Table)]

    def canonical_json(self) -> str:
        """Stable serialisation used for the content id.

        Sorted keys, no whitespace, UTF-8 preserved. Note `ensure_ascii=False`:
        escaping `×` into `\\u00d7` is how a correction pipeline silently
        stopped matching once already (failure C5).
        """
        payload = self.model_dump(mode="json", exclude={"series"})
        return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False)

    @property
    def content_id(self) -> str:
        """Idempotency key. Same content ⇒ same id ⇒ update, never re-create."""
        return hashlib.blake2b(self.canonical_json().encode("utf-8"), digest_size=16).hexdigest()


class Series(BaseModel):
    model_config = {"extra": "forbid"}

    id: str
    title: str
    documents: list[Document]

    def by_index(self, i: int) -> Document:
        for d in self.documents:
            if d.series and d.series.index == i:
                return d
        raise KeyError(f"no document at series index {i}")
